### ISSUE TITLE
some question about the function of MapRegion 

### ISSUE THREAD

**Issue by planktonzp** [edsrzf/mmap-go#20]
why the offset must be a multiple of the system's page size?  I'm a fresher ,maybe the question is stupid but if you can gave me a explanation I'll be very grateful. Have a nice day

**Comment by edsrzf** [comment]
This is a requirement for many POSIX operating systems. See: https://pubs.opengroup.org/onlinepubs/9699919799/functions/mmap.html

> Most implementations require that off and addr are multiples of the page size as returned by sysconf().
