### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by ncw** [edsrzf/mmap-go#21]
I just got bitten by anonymous maps not freeing under windows - this is fixed here 115d23334a12d4ef84813f43786a932350f16c7e

But it isn't in a release, so `go mod` doesn't choose it by default.

Please can you make a release :-)

Thanks

**Comment by ncw** [comment]
Actually, hold the release, I don't think the issue is fixed. Will make another issue shortly...

**Comment by mschoch** [comment]
@ncw are you maintaining a fork?  It's been over a year, and no `v1.0.1` even though at least one important fix is on master.

**Comment by ncw** [comment]
@mschoch I decided in the end to rewrite the code to be the minimal thing I needed https://github.com/rclone/rclone/tree/master/lib/mmap

**Comment by edsrzf** [comment]
1.1.0 is released. Totally understand if you've moved on by this point, but it's done.
