### ISSUE TITLE
Build fails on solaris

### ISSUE THREAD

**Issue by anacrolix** [edsrzf/mmap-go#9]
```
# github.com/edsrzf/mmap-go
../gopath/src/github.com/edsrzf/mmap-go/mmap_unix.go:30: undefined: syscall.Mmap
../gopath/src/github.com/edsrzf/mmap-go/mmap_unix.go:38: undefined: syscall.SYS_MSYNC
../gopath/src/github.com/edsrzf/mmap-go/mmap_unix.go:46: undefined: syscall.SYS_MLOCK
../gopath/src/github.com/edsrzf/mmap-go/mmap_unix.go:54: undefined: syscall.SYS_MUNLOCK
../gopath/src/github.com/edsrzf/mmap-go/mmap_unix.go:62: undefined: syscall.SYS_MUNMAP
```

**Comment by edsrzf** [comment]
Thanks for the report. I have no plans to look into this, but would be happy to accept a pull request to fix it.

**Comment by Toasterson** [comment]
@edsrzf It has been a year that a pull request has been available for this see #15

Are you still maintaining this repository?
Your Software is part of some quite popular Packages including. 
Syncthing https://github.com/syncthing/syncthing
Bleve Indexing https://github.com/blevesearch/bleve
Gitea https://github.com/go-gitea/gitea

All do currently not build on Illumos (Solaris) due to this.

Could you merge the Pull Request?

**Comment by edsrzf** [comment]
@Toasterson try latest master, as of commit https://github.com/edsrzf/mmap-go/commit/14bdcecfd4efdf297ed36700071b05b324132d44. If it works I'll go ahead and release this as 1.0.0 too, so we can do proper semantic versioning on this library.

Sometimes all it takes is a little prod. :wink:

**Comment by Toasterson** [comment]
@edsrzf Glad to help.

That is odd. I looks like x/sys/unix  is still missing a few constants

```text
# github.com/edsrzf/mmap-go [github.com/edsrzf/mmap-go.test]
./mmap_unix.go:38:30: undefined: unix.SYS_MSYNC
./mmap_unix.go:46:30: undefined: unix.SYS_MLOCK
./mmap_unix.go:54:30: undefined: unix.SYS_MUNLOCK
./mmap_unix.go:62:30: undefined: unix.SYS_MUNMAP
FAIL    github.com/edsrzf/mmap-go [build failed]
```

Ah I know whats the problem. Illumos Kernels Use different Constant names than others (Happens in a few Places) 

Have a look at the Constant names in mmap_solaris at #15 they very different.

I guess you will have to have an own Implementation for Illumos and maybe other Unixes that have other Constant names.

BTW. We have a Vagrant Box If that helps testing. 
https://app.vagrantup.com/openindiana/boxes/hipster

**Comment by edsrzf** [comment]
It looks like there are now functions for these syscalls (eg https://godoc.org/golang.org/x/sys/unix#Munlock) so I don't actually need to use the constants anymore. Hopefully switching to those should do the trick. One moment...

**Comment by edsrzf** [comment]
Try again with https://github.com/edsrzf/mmap-go/commit/188cc3b666ba704534fa4f96e9e61f21f1e1ba7c
